### ISSUE TITLE
Failure when generating array of type long

### ISSUE THREAD

**Issue by ikstewa** [confluentinc/avro-random-generator#27]
When attempting to generate an array of type long using 'options' the generations fails with the following error:

```shell
java.lang.RuntimeException: Invalid option for array schema: type org.apache.avro.generic.GenericData$Array, value '[1, 2, 3]'
    at io.confluent.avro.random.generator.Generator.parseOptions(Generator.java:505)
    at io.confluent.avro.random.generator.Generator.generateOption(Generator.java:612)
    at io.confluent.avro.random.generator.Generator.generateObject(Generator.java:373)
    at io.confluent.avro.random.generator.Generator.generateRecord(Generator.java:1345)
    at io.confluent.avro.random.generator.Generator.generateObject(Generator.java:402)
    at io.confluent.avro.random.generator.Generator.generate(Generator.java:367)

```

Example schema:
```json
{
  "namespace": "ksql",
  "name": "testobj",
  "type": "record",
  "fields": [
    {
      "name": "my_long_array",
      "type": {
        "type": "array",
        "items": "long",
        "arg.properties": {
          "options": [
            [ 1, 2, 3 ]
          ]
        }
      }
    }
  ]
}
```

**Comment by C0urante** [comment]
I think this is because [wrapOption](https://github.com/confluentinc/avro-random-generator/blob/1a87c9790f48ed4e76982db3cd1354cdf06b18bb/src/main/java/io/confluent/avro/random/generator/Generator.java#L458) should be recursive for complex types but isn't right now. So, in this case, the values of the options array get parsed as a Java `Collection<Integer>`, which doesn't match the expected type for the schema (should be a `Collection<Long>`).
